# Generated by Django 4.2.8 on 2023-12-24 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Student1',
        ),
    ]
